#ifndef BOOTLOADER_CONFIG_H
#define BOOTLOADER_CONFIG_H

#include <stdint.h>

#define MCU_FLASH_BASE_ADDR UINT32_C(0x08000000)
#define MCU_FLASH_SIZE_BYTES UINT32_C(0x00100000)

#define MCU_FLASH_END_ADDR_EXCLUSIVE \
    (MCU_FLASH_BASE_ADDR + MCU_FLASH_SIZE_BYTES)

#define BOOTLOADER_FLASH_BASE_ADDR \
    MCU_FLASH_BASE_ADDR

#define BOOTLOADER_FLASH_SIZE_BYTES \
    UINT32_C(0x00010000)

#define BOOTLOADER_FLASH_END_ADDR_EXCLUSIVE \
    (BOOTLOADER_FLASH_BASE_ADDR + BOOTLOADER_FLASH_SIZE_BYTES)

#define APPLICATION_FLASH_BASE_ADDR \
    BOOTLOADER_FLASH_END_ADDR_EXCLUSIVE

#define APPLICATION_FLASH_END_ADDR_EXCLUSIVE \
    MCU_FLASH_END_ADDR_EXCLUSIVE

#define APPLICATION_FLASH_MAX_SIZE_BYTES \
    (APPLICATION_FLASH_END_ADDR_EXCLUSIVE - APPLICATION_FLASH_BASE_ADDR)

/* 编译期检查：Application 必须从 0x08010000 开始 */
_Static_assert(
    APPLICATION_FLASH_BASE_ADDR == UINT32_C(0x08010000),
    "Application Flash base address must be 0x08010000"
);

_Static_assert(
    BOOTLOADER_FLASH_END_ADDR_EXCLUSIVE <= APPLICATION_FLASH_BASE_ADDR,
    "Bootloader and application Flash regions overlap"
);

#define BOOT_PROTOCOL_MAX_DATA_LENGTH \
    UINT32_C(256)

#define BOOTLOADER_UPGRADE_TIMEOUT_MS \
    UINT32_C(5000)

_Static_assert(
    APPLICATION_FLASH_END_ADDR_EXCLUSIVE <= MCU_FLASH_END_ADDR_EXCLUSIVE,
    "Application Flash region exceeds MCU Flash"
);

#endif
